### ISSUE TITLE
Generic prompts

### ISSUE THREAD

**Issue by CMCDragonkai** [Seldaek/hidden-input#1]
Is there an generic library that offers the ability to prompt the user for passwords, normal plain text, and menu options all cross platform?

**Comment by Seldaek** [comment]
Not sure what you mean by normal plain text/menu options. This code just allows you to prompt for plain text input without printing it out to the terminal, so it's typically useful for passwords but can be used for anything really.

**Comment by CMCDragonkai** [comment]
Oh I meant, what if I don't want to hide the text? Can it be used for that?

**Comment by Seldaek** [comment]
Ah I see, well no it can't be used for that, but that is much simpler and
most programming languages will offer you a way to prompt the user for (non
hidden) input usually calling a simple function.

**Comment by CMCDragonkai** [comment]
Is there one that is cross platform for PHP?

**Comment by Seldaek** [comment]
in php `fgets(STDIN)` will get you whatever the user types in
