### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by Pajamaman** [Seldaek/hidden-input#2]
I followed you answer on StackOverflow to this repo: http://stackoverflow.com/a/12126105/1015595

I tried replicating the code you posted there:

```
<?php
    echo 'Enter password: ';
    exec('bin/hiddeninput.exe', $password);

    echo 'Password was: ' . $password;
?>
```

However running this page throws an error:

```
 Notice: Array to string conversion in C:\WampServer\www\hiddeninput\test.php on line 5
```

**Comment by Seldaek** [comment]
Ah well that is me being a moron :) I updated the code sample and actually tested it this time..

Here is a copy:

``` php
<?php

echo 'Enter password: ';
$password = exec('hiddeninput.exe');
echo PHP_EOL;

echo 'Password was: ' . $password . PHP_EOL;
```
